language: python

python:
    - "2.7"
    - "3.3"
install:
    - pip install pytest-cov --use-mirrors
    - pip install coveralls --use-mirrors

script: py.test tests/test_scheduling.py -v --cov greenclock --cov-report term-missing

after_success:
    - coveralls
